### ISSUE TITLE
Videos not playing

### ISSUE THREAD

**Issue by goggato** [psychon-night/bypass-youtube-adblock-blocker#1]
The anti adblock screen is gone now and I can click play, but the video screen stays black and the video doesn't play

**Comment by puxis7** [comment]
Same for me. I can press play, but video length is not available and play doesn't start. It's just black screen.

**Comment by psychon-night** [comment]
Make sure you update your uBlock filters. I also encountered that issue, that is what solved it for me.

Are you using the modified `desktop_polymer_enable_wil_icons.js` file? It's possible that your YouTube pulled an update and bricked that. If this is the case, you'll need to:
- Disable the Request Interceptor rules
- Hard refresh YouTube (Ctrl+Shift+R)
- Update your uBlock filters

Once you do that, add [these rules](https://raw.githubusercontent.com/psychon-night/bypass-youtube-adblock-blocker/main/ublockRulesFromReddit) to uBlock's `My Filters` tab

**Comment by mahmoud-syr** [comment]
Clearing the cache and clicking update on the uOrigin worked for me.
Really nice work guys!!!
